from patch_curriculum import make_q
from generate_all_curriculum import p1_quizzes

p2_quizzes = {
    "lesson-2-1": [
        make_q("q-2-1-1", "What is the total dimension of the unitary operator matrix for an n-qubit quantum circuit?", ["n x n", "2ⁿ x 2ⁿ", "2n x 2n", "n² x n²"], 1, "An n-qubit state space has 2ⁿ dimensions, so state-vector operations map to 2ⁿ x 2ⁿ unitary matrices."),
        make_q("q-2-1-2", "Which multi-qubit gate creates entanglement by flipping the target qubit if the control qubit is |1⟩?", ["Hadamard", "CNOT (CX)", "Pauli-Z", "Phase S"], 1, "The CNOT (CX) gate flips the target qubit if and only if the control qubit is in state |1⟩."),
        make_q("q-2-1-3", "In Qiskit, what code adds a CNOT gate with control qubit 0 and target qubit 1?", ["qc.cx(0, 1)", "qc.cnot(1, 0)", "qc.cz(0, 1)", "qc.swap(0, 1)"], 0, "qc.cx(0, 1) adds a controlled-NOT gate with control 0 and target 1."),
        make_q("q-2-1-4", "What is the output bitstring state after applying CNOT(q0 -> q1) to input state |10⟩?", ["|10⟩", "|11⟩", "|00⟩", "|01⟩"], 1, "Control qubit 0 is |1⟩, so CNOT flips target qubit 1 from |0⟩ to |1⟩, resulting in state |11⟩."),
        make_q("q-2-1-5", "Which 3-qubit gate flips the target qubit if and only if BOTH control qubits are |1⟩?", ["Toffoli (CCX)", "Fredkin (CSWAP)", "Bell gate", "Deutsch gate"], 0, "The Toffoli (Controlled-Controlled-NOT) gate acts on 2 controls and 1 target.")
    ],
    "lesson-2-2": [
        make_q("q-2-2-1", "What quantum phenomenon allows probability amplitudes of wrong answer paths to cancel out?", ["Constructive Interference", "Destructive Interference", "Decoherence", "Measurement"], 1, "Destructive interference cancels out negative and positive complex probability amplitudes for wrong answers."),
        make_q("q-2-2-2", "What is the net unitary transformation resulting from applying Hadamard twice consecutively (H H |0⟩)?", ["|0⟩", "|1⟩", "|+⟩", "|-⟩"], 0, "Since H² = I (Identity matrix), applying two consecutive Hadamards returns the original state |0⟩."),
        make_q("q-2-2-3", "In Mach-Zehnder optical interferometers or quantum circuits, what rotates relative phases into measurable constructive interference?", ["Beamsplitters / Hadamard gates", "Resistors", "Absorbers", "Detectors"], 0, "Beamsplitters (and Hadamards) combine phase-shifted pathways to create interference patterns."),
        make_q("q-2-2-4", "If state amplitudes are +1/√2 and -1/√2 when combined by a Hadamard gate, what is the resulting amplitude for state |1⟩?", ["0.0", "1.0", "1/√2", "-1.0"], 1, "Phase cancellation directs all probability density into state |1⟩."),
        make_q("q-2-2-5", "Why is quantum interference crucial for computational speedups?", ["It speeds up electrical signals", "It amplifies correct solution probabilities while suppressing incorrect ones", "It eliminates cooling requirements", "It deletes memory"], 1, "Interference shifts probability amplitude toward the correct answers before final measurement.")
    ],
    "lesson-2-3": [
        make_q("q-2-3-1", "How many oracle queries does the Deutsch-Jozsa algorithm require to classify a function as constant or balanced?", ["1 query", "2ⁿ⁻¹ + 1 queries", "2ⁿ queries", "n queries"], 0, "Deutsch-Jozsa requires exactly 1 quantum oracle query, demonstrating exponential speedup over classical worst-case."),
        make_q("q-2-3-2", "What is defined as a 'balanced' function f(x) in the Deutsch-Jozsa problem?", ["f(x) returns 0 for all x", "f(x) returns 0 for exactly half of inputs and 1 for the other half", "f(x) returns 1 for all x", "f(x) returns random numbers"], 1, "A balanced function outputs 0 for exactly half of its domain and 1 for the other half."),
        make_q("q-2-3-3", "What measurement outcome indicates that f(x) is constant in Deutsch-Jozsa?", ["All 0s bitstring |00...0⟩", "All 1s bitstring |11...1⟩", "Equal split", "Alternating 0s and 1s"], 0, "Measuring all 0s (|00...0⟩) guarantees the function is constant; any non-zero outcome proves it is balanced."),
        make_q("q-2-3-4", "Which state prep technique applies phase kickback in Deutsch-Jozsa?", ["Target qubit initialized in state |–⟩ = (|0⟩ - |1⟩)/√2", "Target qubit in state |0⟩", "All qubits in state |1⟩", "No state prep"], 0, "Initializing the target qubit in |–⟩ induces phase kickback (-1)^f(x) onto input qubits."),
        make_q("q-2-3-5", "What classical query complexity does Deutsch-Jozsa beat?", ["O(2ⁿ⁻¹) worst-case classical queries", "O(1) classical queries", "O(n²)", "O(log n)"], 0, "Classical deterministic algorithms require 2ⁿ⁻¹ + 1 queries in the worst case.")
    ],
    "lesson-2-4": [
        make_q("q-2-4-1", "What query complexity does Grover's algorithm achieve for searching an unstructured database of N items?", ["O(√N)", "O(N)", "O(N²)", "O(log N)"], 0, "Grover's algorithm achieves quadratic quantum speedup O(√N) over classical O(N) search."),
        make_q("q-2-4-2", "What operation does the Grover Oracle perform on the target solution state |ω⟩?", ["Bit flips target", "Flips the phase of |ω⟩ to -|ω⟩", "Measures state", "Deletes target"], 1, "The Grover oracle applies a phase flip U_ω|x⟩ = (-1)^(f(x))|x⟩ to the target state."),
        make_q("q-2-4-3", "What is the second main component of a Grover iteration after the Oracle phase flip?", ["Grover Diffusion Operator (Inversion about the mean)", "Hadamard reset", "Fourier transform", "Random rotation"], 0, "The Grover Diffusion Operator reflects amplitudes about the mean amplitude, amplifying the target state."),
        make_q("q-2-4-4", "How many Grover iterations are optimal for finding 1 marked item in N = 2ⁿ states?", ["≈ (π/4) √N", "N iterations", "2ⁿ iterations", "1 iteration"], 0, "The optimal number of Grover iterations is approximately (π/4) √N."),
        make_q("q-2-4-5", "What happens if you run TOO MANY Grover iterations beyond the optimal count?", ["Target amplitude continues to grow", "Target amplitude over-rotates past the peak and decreases (overcooking)", "Circuit crashes", "Qubits decohere to zero"], 1, "Grover's algorithm rotates state vectors in a 2D subspace; over-rotating causes amplitude to decline.")
    ],
    "lesson-2-5": [
        make_q("q-2-5-1", "What is the gate complexity of the Quantum Fourier Transform (QFT) on n qubits?", ["O(n²)", "O(2ⁿ)", "O(n 2ⁿ)", "O(n³)"], 0, "QFT requires only O(n²) quantum gates (Hadamard + Controlled Phase Rotations)."),
        make_q("q-2-5-2", "What classical algorithm speedup is matched/exceeded by QFT?", ["Fast Fourier Transform (FFT) requiring O(n 2ⁿ) operations", "Bubble Sort", "Dijkstra's", "Binary Search"], 0, "QFT maps amplitude distributions in O(n²) gates versus classical FFT's O(n 2ⁿ) operations."),
        make_q("q-2-5-3", "In Qiskit QFT implementations, why are SWAP gates applied at the end of the circuit?", ["To reverse qubit order back to standard big-endian convention", "To clear memory", "To add noise", "To measure qubits"], 0, "Controlled rotations output bits in reversed order, requiring SWAP gates to restore proper bit ordering."),
        make_q("q-2-5-4", "What fundamental quantum algorithms rely directly on QFT as a sub-routine?", ["Shor's Algorithm and Quantum Phase Estimation (QPE)", "Grover's Search", "Deutsch-Jozsa", "Classical Gradient Descent"], 0, "QFT is the central subroutine in Quantum Phase Estimation (QPE) and Shor's factoring algorithm."),
        make_q("q-2-5-5", "What controlled rotation gate R_k is used in QFT circuits?", ["Controlled phase rotation diag(1, e^(2πi / 2ᵏ))", "CNOT", "Toffoli", "Pauli-X"], 0, "QFT uses controlled phase shifts R_k with phase angle 2π / 2ᵏ.")
    ],
    "lesson-2-6": [
        make_q("q-2-6-1", "What computational task does Shor's algorithm solve in polynomial time O((log N)³)?", ["Prime factorization of large composite integers N", "Database searching", "Graph coloring", "Image compression"], 0, "Shor's algorithm factors integers in polynomial time O((log N)³)."),
        make_q("q-2-6-2", "To what mathematical problem does Shor's algorithm reduce prime integer factorization?", ["Modular Period Finding (f(x) = aˣ mod N)", "Linear Regression", "Matrix Inversion", "Travelling Salesperson"], 0, "Factoring N reduces to finding the period r of the function f(x) = aˣ mod N."),
        make_q("q-2-6-3", "Which classical public-key cryptosystem is vulnerable to Shor's factoring algorithm?", ["RSA Encryption", "AES-256", "SHA-256", "One-Time Pad"], 0, "RSA security relies on hardness of factoring large integers, which Shor's algorithm breaks."),
        make_q("q-2-6-4", "What quantum algorithm subroutine extracts the period r in Shor's algorithm?", ["Quantum Phase Estimation (QPE) using QFT", "Grover's search", "VQE", "QAOA"], 0, "QPE with QFT measures phase values that reveal the period r via continued fractions."),
        make_q("q-2-6-5", "Once period r is found (if r is even and a^(r/2) ≢ -1 mod N), how are prime factors derived classically?", ["gcd(a^(r/2) ± 1, N)", "a * r", "N / r", "r² + 1"], 0, "The classical Euclidean algorithm computes prime factors via greatest common divisor gcd(a^(r/2) ± 1, N).")
    ],
    "lesson-2-7": [
        make_q("q-2-7-1", "What does NISQ stand for in quantum computing?", ["Noisy Intermediate-Scale Quantum", "New Integrated Silicon Quantum", "Non-Interfering Qubit Systems", "Next-gen Scalable Quantum"], 0, "NISQ stands for Noisy Intermediate-Scale Quantum (50 to 1000 qubits without full fault tolerance)."),
        make_q("q-2-7-2", "Why cannot NISQ devices execute million-gate quantum algorithms like Shor's factoring?", ["Gate noise and decoherence accumulate before circuit completion", "Lack of electricity", "CPUs are too slow", "Hard drives are full"], 0, "Accumulated gate errors and short coherence times destroy quantum states in deep circuits."),
        make_q("q-2-7-3", "What hybrid computing paradigm is tailored specifically for NISQ constraints?", ["Variational Quantum Algorithms (VQAs)", "Classical brute force", "Tape drives", "Mainframes"], 0, "VQAs use shallow quantum circuits and classical optimization loops to maximize NISQ utility."),
        make_q("q-2-7-4", "What measure describes the number of operational qubits and circuit depth a QPU can run reliably?", ["Quantum Volume (QV)", "Megahertz", "Gigabytes", "TFLOPS"], 0, "Quantum Volume quantifies QPU fidelity, connectivity, and depth performance."),
        make_q("q-2-7-5", "In NISQ algorithms, where does parameter optimization take place?", ["On a classical CPU / GPU", "On the QPU", "In a vacuum tube", "In the fridge controller"], 0, "Classical computers run gradient descent loops while the QPU evaluates state expectation values.")
    ],
    "lesson-2-8": [
        make_q("q-2-8-1", "What physical phenomenon does the T1 relaxation time quantify in qubits?", ["Thermal relaxation (energy loss from |1⟩ to ground state |0⟩)", "Phase jitter", "Measurement delay", "Laser power"], 0, "T1 measures the characteristic time for an excited qubit in state |1⟩ to decay to ground state |0⟩."),
        make_q("q-2-8-2", "What loss of quantum information does T2 dephasing time measure?", ["Loss of relative phase coherence in superposition states", "Loss of physical qubits", "Loss of power", "Loss of memory"], 0, "T2 measures dephasing, where environmental noise scrambles relative phase angle ϕ."),
        make_q("q-2-8-3", "How does decoherence affect pure states on the Bloch sphere over time?", ["Shrinks state vector into the interior of the Bloch sphere (mixed state)", "Expands vector past surface", "Pushes vector to north pole instantly", "No effect"], 0, "Decoherence transforms pure surface states into mixed state ensembles inside the Bloch ball."),
        make_q("q-2-8-4", "What type of error is caused by imperfect microwave pulses during single-qubit gate execution?", ["Coherent gate execution error", "T1 decay", "Cosmic rays", "Measurement drift"], 0, "Pulse length or amplitude miscalibrations produce systematic coherent over-rotation errors."),
        make_q("q-2-8-5", "What is the relationship between T1 and T2 dephasing time?", ["T2 ≤ 2 * T1", "T2 = 100 * T1", "T2 is always larger than 1 second", "T2 = T1²"], 0, "Dephasing T2 is bounded by energy relaxation time: T2 ≤ 2 * T1.")
    ],
    "lesson-2-9": [
        make_q("q-2-9-1", "How does Zero-Noise Extrapolation (ZNE) mitigate noise without extra physical logical qubits?", ["Scales circuit noise artificially (λ=1,3,5) and extrapolates expectation back to zero-noise limit λ=0", "Cools fridge", "Increases shots", "Deletes noise"], 0, "ZNE intentionally scales noise levels and fits a polynomial curve back to zero noise λ=0."),
        make_q("q-2-9-2", "What technique stretches pulse durations or inserts unitaries (U U†) to amplify noise in ZNE?", ["Digital / Pulse Noise Scaling", "Quantum Error Correction", "Hardware replacement", "Frequency hopping"], 0, "Digital noise scaling replaces gate U with U U† U to artificially increase circuit noise depth."),
        make_q("q-2-9-3", "What error mitigation method uses a confusion matrix to fix readout errors?", ["Readout Error Mitigation (Measurement Mitigation)", "ZNE", "Probabilistic Error Cancellation", "Dynamiting"], 0, "Readout mitigation constructs an assignment matrix to invert state measurement misclassifications."),
        make_q("q-2-9-4", "What is the primary difference between Error Mitigation and Fault-Tolerant Error Correction (QEC)?", ["Mitigation uses software post-processing without extra physical qubits; QEC uses redundant physical qubits per logical qubit", "They are the same", "QEC requires no hardware", "Mitigation only works on GPUs"], 0, "Software mitigation reduces noise in expectation values without the overhead of fault-tolerant QEC codes."),
        make_q("q-2-9-5", "Which open-source Python library is widely used for error mitigation with Qiskit?", ["Mitiq", "NumPy", "TensorFlow", "Pandas"], 0, "Mitiq is a leading Python library for error mitigation techniques like ZNE and PEC.")
    ],
    "lesson-2-10": [
        make_q("q-2-10-1", "What is the primary function of the Qiskit Transpiler?", ["Transforms high-level circuits into native gate sets compatible with hardware coupling maps", "Translates Python to Java", "Simulates Aer", "Deletes gates"], 0, "The transpiler maps abstract circuits to QPU native gate sets and physical qubit connectivity."),
        make_q("q-2-10-2", "What optimization level in Qiskit transpilation executes aggressive gate synthesis and SWAP routing?", ["optimization_level=3", "optimization_level=0", "level=-1", "level=100"], 0, "Qiskit offers optimization levels 0 to 3; level 3 applies maximum heuristic synthesis."),
        make_q("q-2-10-3", "Why must SWAP gates be inserted during transpilation for physical QPUs?", ["When two qubits in a 2-qubit gate are not directly connected on the hardware topology map", "To make circuit faster", "To add noise", "To measure qubits"], 0, "Physical superconducting QPUs have restricted nearest-neighbor coupling topologies."),
        make_q("q-2-10-4", "What Qiskit Runtime primitive is optimized for computing expectation values ⟨ψ|H|ψ⟩ on QPU hardware?", ["Estimator primitive", "Sampler primitive", "AerSimulator", "JobManager"], 0, "The Estimator primitive evaluates observable expectation values ⟨H⟩ efficiently."),
        make_q("q-2-10-5", "What Qiskit Runtime primitive is optimized for generating probability distributions and outcome bitstrings?", ["Sampler primitive", "Estimator primitive", "PulseEngine", "Transpiler"], 0, "The Sampler primitive samples output bitstrings and probability distributions from execution shots.")
    ]
}

p3_quizzes = {
    "lesson-3-1": [
        make_q("q-3-1-1", "What are Parameterized Quantum Circuits (PQCs) often called in QML literature?", ["Variational Quantum Circuits or Ansätze", "Lookup tables", "Classical networks", "Static gates"], 0, "PQCs contain adjustable continuous parameters θ adjusted by optimizers."),
        make_q("q-3-1-2", "Which single-qubit gates provide continuous parameterized rotation in PQCs?", ["Rx(θ), Ry(θ), Rz(θ)", "Hadamard, X, Z", "CNOT, SWAP", "Toffoli"], 0, "Rx, Ry, and Rz take continuous angle arguments θ."),
        make_q("q-3-1-3", "What is the purpose of entangling layers (e.g. CNOT rings) in an Ansatz circuit?", ["Creates multi-qubit quantum correlations across feature spaces", "Reduces depth", "Cools qubits", "Deletes state"], 0, "Entangling layers generate non-local quantum correlations required for expressibility."),
        make_q("q-3-1-4", "What defines an Strongly Entangling Layers ansatz in PennyLane / Qiskit?", ["Alternating single-qubit rotations and entangling CNOT/CZ rings", "Only Hadamard gates", "Only measurement gates", "Random noise"], 0, "Strongly entangling layers combine multi-axis rotations with entangling maps."),
        make_q("q-3-1-5", "How is circuit depth defined in a Parameterized Quantum Circuit?", ["Number of sequential gate layers executed from input to measurement", "Number of qubits", "Number of shots", "Number of parameters"], 0, "Depth is the maximum number of sequential gate operations along any qubit line.")
    ],
    "lesson-3-2": [
        make_q("q-3-2-1", "Which encoding scheme packs 2ⁿ classical feature values into the state amplitudes of n qubits?", ["Amplitude Encoding", "Basis Encoding", "Angle Encoding", "One-Hot Encoding"], 0, "Amplitude encoding stores 2ⁿ features in n qubits via normalized state vector |ψ_x⟩ = ∑ x_i |i⟩."),
        make_q("q-3-2-2", "How many qubits are required to encode an M-dimensional classical vector using Angle Encoding?", ["M qubits", "log₂ M qubits", "M² qubits", "1 qubit"], 0, "Angle encoding assigns each feature x_j to a single qubit rotation angle θ_j = x_j."),
        make_q("q-3-2-3", "What is the main advantage of Basis Encoding for binary classical data?", ["Maps binary strings directly to computational basis state vectors (e.g., 101 -> |101⟩)", "Exponential compression", "Infinite precision", "Requires no gates"], 0, "Basis encoding maps classical binary strings x ∈ {0,1}ⁿ directly to quantum state |x⟩."),
        make_q("q-3-2-4", "Why is Amplitude Encoding state preparation computationally expensive on NISQ devices?", ["Requires O(2ⁿ) gate depth to prepare arbitrary state vectors", "Requires too many classical bits", "Does not support floating points", "Requires no entanglement"], 0, "Arbitrary state vector preparation requires deep O(2ⁿ) decomposition circuits."),
        make_q("q-3-2-5", "In Qiskit's ZZFeatureMap, what non-linear feature interactions are encoded?", ["Pairwise feature products x_i * x_j via 2-qubit R_ZZ gates", "Linear sums", "Ratios", "Random noise"], 0, "ZZFeatureMap uses R_ZZ(2(π - x_i)(π - x_j)) gates to capture non-linear feature interactions.")
    ],
    "lesson-3-3": [
        make_q("q-3-3-1", "What physical property does the Variational Quantum Eigensolver (VQE) compute for a Hamiltonian H?", ["Ground state energy E₀", "Particle count", "Temperature", "Frequency"], 0, "VQE computes the lowest eigenvalue (ground state energy E₀) of a quantum Hamiltonian H."),
        make_q("q-3-3-2", "What mathematical theorem guarantees that expectation value ⟨ψ(θ)|H|ψ(θ)⟩ is always ≥ true ground energy E₀?", ["Rayleigh-Ritz Variational Principle", "No-Cloning Theorem", "Born Rule", "Bayes Theorem"], 0, "The Variational Principle guarantees ⟨H⟩_θ ≥ E₀ for any trial wave function."),
        make_q("q-3-3-3", "In VQE, which device computes the trial state expectation value ⟨H⟩_θ?", ["Physical QPU or Quantum Simulator", "Classical CPU", "Hard Drive", "Network Switch"], 0, "The QPU evaluates energy expectation values for parameter set θ."),
        make_q("q-3-3-4", "Which classical optimizer is gradient-free and robust against NISQ shot noise in VQE?", ["SPSA (Simultaneous Perturbation Stochastic Approximation) or COBYLA", "Adam", "SGD", "Newton-Raphson"], 0, "SPSA and COBYLA perform well under stochastic shot noise on physical QPUs."),
        make_q("q-3-3-5", "What chemistry problem is a canonical benchmark for VQE?", ["Calculating ground state binding energy of Hydrogen molecule (H₂)", "Sorting chemical names", "Balancing equations", "Pumping water"], 0, "Finding the electronic ground state energy of H₂ or LiH is a classic VQE application.")
    ],
    "lesson-3-4": [
        make_q("q-3-4-1", "What optimization problem domain is targeted by QAOA?", ["Combinatorial Optimization (e.g., Max-Cut, Graph Coloring, QUBO)", "Linear Regression", "Image Segmentation", "Sound Synthesis"], 0, "QAOA targets NP-hard combinatorial optimization problems mapped to Ising spin glasses."),
        make_q("q-3-4-2", "What are the two alternating Hamiltonians applied in a depth-p QAOA circuit?", ["Cost Hamiltonian H_C and Mixer Hamiltonian H_M", "Kinetic and Potential", "X and Y", "Primary and Secondary"], 0, "QAOA alternates exponentiated Cost unitary e^(-iγ H_C) and Mixer unitary e^(-iβ H_M)."),
        make_q("q-3-4-3", "What is the standard Mixer Hamiltonian used in QAOA for unconstrained problems?", ["H_M = ∑ X_i (sum of Pauli-X operators across qubits)", "H_M = ∑ Z_i", "H_M = I", "H_M = ∑ Y_i"], 0, "The standard transverse-field mixer is H_M = ∑ X_i."),
        make_q("q-3-4-4", "What parameter angles are optimized in QAOA during the classical loop?", ["γ (gamma) and β (beta) angle vectors of length p", "Learning rates", "Shot counts", "Qubit frequencies"], 0, "QAOA optimizes 2p variational parameters (γ_1..γ_p, β_1..β_p)."),
        make_q("q-3-4-5", "What graph problem is commonly solved as an introductory QAOA demonstration?", ["Max-Cut problem", "Shortest Path", "Binary Search", "Matrix Multiplication"], 0, "Max-Cut partitions graph vertices to maximize cut edge weights.")
    ],
    "lesson-3-5": [
        make_q("q-3-5-1", "How does a Quantum Support Vector Machine (QSVM) evaluate similarity between data points x_i and x_j?", ["Computes quantum kernel Gram matrix K_ij = |⟨Φ(x_i)|Φ(x_j)⟩|²", "Euclidean distance", "Dot product in 2D", "String comparison"], 0, "QSVM evaluates fidelity overlaps between feature-mapped quantum states |Φ(x)⟩."),
        make_q("q-3-5-2", "What advantage does a Quantum Kernel offer over classical RBF kernels?", ["Accesses exponentially large feature Hilbert space ℂ^(2ⁿ) inaccessible to classical kernels", "Faster addition", "Uses less disk space", "Requires no data"], 0, "Quantum feature maps map data into high-dimensional Hilbert spaces with non-classical inner products."),
        make_q("q-3-5-3", "Where is the SVM hyperplane dual optimization problem solved in a QSVM architecture?", ["On a classical CPU / GPU using quadratic programming solvers", "Inside the QPU", "In a vacuum", "On a router"], 0, "The QPU builds the Gram matrix K; classical solvers solve the quadratic SVM optimization."),
        make_q("q-3-5-4", "What circuit technique estimates the inner product overlap |⟨Φ(x_i)|Φ(x_j)⟩|²?", ["Swap Test or Compute-Uncompute circuit U†(x_j) U(x_i)", "Hadamard alone", "Pauli-X", "Measurement in X-basis"], 0, "Applying U(x_i) followed by U†(x_j) measures ground state probability |0...0⟩."),
        make_q("q-3-5-5", "What Qiskit Machine Learning class implements quantum kernel calculations?", ["FidelityQuantumKernel", "LinearRegression", "KMeans", "DenseLayer"], 0, "FidelityQuantumKernel computes quantum state fidelity matrices.")
    ],
    "lesson-3-6": [
        make_q("q-3-6-1", "What layers compose a Quantum Neural Network (QNN) architecture?", ["Feature Encoding Layer, Parameterized Quantum Circuit (PQC), and Measurement Observables", "Input, Conv, Pooling", "Dense, Dropout, Softmax", "SQL, API, UI"], 0, "QNNs comprise data encoding, trainable PQC layers, and measurement expectation operators."),
        make_q("q-3-6-2", "How is output prediction derived from a QNN for classification?", ["Evaluating observable expectation value ⟨Z_i⟩ or measuring probability distribution", "Counting gate lines", "Reading CPU RAM", "Checking clock speed"], 0, "Expectation values ⟨ψ(θ,x)|Z|ψ(θ,x)⟩ are mapped to continuous class predictions."),
        make_q("q-3-6-3", "What open-source library seamlessly integrates PennyLane QNN layers into PyTorch and TensorFlow?", ["PennyLane qml.qnn.TorchLayer", "Scikit-learn", "OpenCV", "Flask"], 0, "TorchLayer wraps PennyLane quantum nodes as native PyTorch nn.Module layers."),
        make_q("q-3-6-4", "How are gradients propagated through PyTorch / QNN hybrid models?", ["PyTorch autograd calls the Parameter-Shift rule for quantum layer backward passes", "Manual calculation", "Finite differences only", "Random search"], 0, "TorchLayer registers quantum backward passes using analytic parameter-shift gradients."),
        make_q("q-3-6-5", "What loss function is paired with QNN output expectation values for classification?", ["Binary Cross-Entropy or Mean Squared Error", "L1 Norm", "Huber Loss", "KL Divergence"], 0, "Expectations scaled to [-1, 1] or [0, 1] are trained using MSE or BCE loss.")
    ],
    "lesson-3-7": [
        make_q("q-3-7-1", "What is a Quantum Kernel Method?", ["A QML approach using QPU feature maps to compute kernel values K(x, y) for kernelized ML algorithms", "A Linux kernel extension", "A GPU driver", "A memory buffer"], 0, "Quantum kernel methods compute Hilbert space inner products for classical kernel algorithms."),
        make_q("q-3-7-2", "What property must a valid Quantum Kernel matrix K satisfy?", ["Symmetric and Positive Semi-Definite (PSD)", "Asymmetric", "Negative definite", "Diagonal only"], 0, "Mercer's theorem requires kernel matrices to be symmetric and positive semi-definite."),
        make_q("q-3-7-3", "What happens if quantum feature map depth is set too shallow without entanglement?", ["Kernel collapses into classically simulable product kernel without quantum advantage", "Kernel explodes", "QPU crashes", "Perfect accuracy"], 0, "Shallow unentangled feature maps can be efficiently computed by classical computers."),
        make_q("q-3-7-4", "What phenomenon occurs if a Quantum Kernel feature map is overly complex or expressive?", ["Kernel Exponential Concentration (all off-diagonal K_ij values approach 0)", "Instant convergence", "Zero loss", "Infinite memory"], 0, "Overly expressive feature maps cause state inner products to concentrate near 0."),
        make_q("q-3-7-5", "Which classical algorithms benefit directly from Quantum Kernel inputs?", ["Support Vector Machines (SVM), Kernel Ridge Regression, and Kernel PCA", "Decision Trees", "K-Means", "Naïve Bayes"], 0, "Kernelized algorithms accept QPU-computed Gram matrices directly.")
    ],
    "lesson-3-8": [
        make_q("q-3-8-1", "What is the Parameter-Shift Rule in QML?", ["An exact analytical gradient formula evaluating expectation values at shifted parameters θ ± s", "A numerical approximation", "A random search", "A classical backprop"], 0, "The Parameter-Shift rule computes exact analytic gradients ∂⟨H⟩/∂θ = (⟨H⟩_(θ+s) - ⟨H⟩_(θ-s)) / (2 sin s)."),
        make_q("q-3-8-2", "What shift value s is used for standard single-qubit rotation gates Rx, Ry, Rz with generator G = Pauli / 2?", ["s = π / 2 (90 degrees)", "s = 0.001", "s = π", "s = 2π"], 0, "For generator spectrum ±1/2, the exact shift amount is s = π / 2."),
        make_q("q-3-8-3", "Why is Parameter-Shift superior to classical Finite Differences (f(θ+ε)-f(θ))/ε on hardware?", ["Avoids numerical instability and shot noise errors caused by tiny ε steps", "Requires zero executions", "Runs faster", "Does not use qubits"], 0, "Finite differences with small ε fails on QPUs due to shot noise; parameter-shift uses large s=π/2 steps."),
        make_q("q-3-8-4", "How many total circuit executions are required to evaluate the gradient vector of a PQC with M parameters?", ["2 * M circuit evaluations", "M² evaluations", "1 evaluation", "2ᴹ evaluations"], 0, "Each parameter requires 2 shifted evaluations (θ + π/2 and θ - π/2), yielding 2M total runs."),
        make_q("q-3-8-5", "Does the Parameter-Shift Rule work on physical quantum hardware QPUs?", ["Yes, it is designed specifically for execution on physical QPUs", "No, simulator only", "No, GPU only", "No, CPU only"], 0, "Parameter-shift executes real circuits on hardware to yield exact physical gradients.")
    ],
    "lesson-3-9": [
        make_q("q-3-9-1", "What is a Barren Plateau in QML optimization landscapes?", ["A phenomenon where gradient variance vanishes exponentially with qubit count n: Var(∂L/∂θ) ∈ O(2⁻ⁿ)", "A flat loss function", "A GPU error", "A classical memory leak"], 0, "Barren plateaus cause gradients to decay exponentially O(2⁻ⁿ), making deep random PQCs untrainable."),
        make_q("q-3-9-2", "What causes Barren Plateaus in variational quantum circuits?", ["Overly deep random ansätze forming approximate 2-designs across Hilbert space", "Low shot count", "Slow CPUs", "Lack of qubits"], 0, "Haar-random unitaries spread state vectors uniformly over exponentially vast Hilbert space."),
        make_q("q-3-9-3", "How does using local cost functions (measuring single qubits) help prevent barren plateaus compared to global cost functions?", ["Local cost functions exhibit polynomial gradient decay instead of exponential decay", "Eliminates gradient descent", "Increases depth", "Deletes qubits"], 0, "Local observables bound gradient concentration, maintaining polynomial trainability."),
        make_q("q-3-9-4", "What initialization strategy mitigates barren plateaus by starting near identity?", ["Identity / Small-parameter initialization (θ ≈ 0)", "Random uniform initialization", "Large weights", "Constant 1s"], 0, "Initializing parameters near 0 keeps initial unitaries close to identity, avoiding Haar randomness."),
        make_q("q-3-9-5", "How does layer-wise training combat barren plateaus?", ["Trains shallow sub-circuits incrementally before adding deeper layers", "Trains all parameters simultaneously", "Randomly skips layers", "Uses no parameters"], 0, "Layer-wise training restricts active parameter space to manageable shallow dimensions.")
    ],
    "lesson-3-10": [
        make_q("q-3-10-1", "What defines a Hybrid Classical-Quantum Architecture?", ["An architecture orchestrating CPUs, GPUs, and QPUs in a unified compute graph", "A computer with two CPUs", "A hybrid car", "A cloud server"], 0, "Hybrid architectures combine classical preprocessing, quantum PQC execution, and classical optimizers."),
        make_q("q-3-10-2", "What role do classical GPUs play in high-performance hybrid QML workflows?", ["Accelerating classical tensor operations and running high-speed quantum circuit state-vector simulations", "Cooling the QPU", "Storing data", "Executing microwave pulses"], 0, "GPUs accelerate classical neural layers and simulate large quantum circuits via cuQuantum."),
        make_q("q-3-10-3", "In an enterprise QML pipeline, what component handles API request routing, authentication, and job queuing?", ["Classical CPU server (e.g., FastAPI / Node.js)", "QPU dilution fridge", "GPU buffer", "Switch"], 0, "CPUs handle application logic, user auth, data pipelines, and job scheduling."),
        make_q("q-3-10-4", "Why are hybrid models preferred over pure quantum models in current industry deployments?", ["Leverages classical strengths for feature extraction while using QPUs only where quantum advantage exists", "QPUs cannot display graphics", "GPUs are cheaper", "No quantum software exists"], 0, "Hybrid workflows minimize NISQ noise impact while retaining quantum representation power."),
        make_q("q-3-10-5", "Which open-source framework provides GPU-accelerated quantum circuit simulation with PyTorch integration?", ["cuQuantum with PennyLane / Qiskit Aer GPU", "TensorFlow CPU", "OpenCV", "Scipy"], 0, "NVIDIA cuQuantum provides GPU-accelerated state-vector and tensor network simulation engines.")
    ]
}

print("Enrichment module loaded successfully.")
