import json
from patch_curriculum import make_q, make_interphasory_quiz
from generate_all_curriculum import p1_quizzes
from enrich_all_lessons import p2_quizzes, p3_quizzes

p4_quizzes = {
    "lesson-4-1": [
        make_q("q-4-1-1", "What are the two competing quantum/classical components in a Quantum Generative Adversarial Network (QGAN)?", ["Quantum/Classical Generator and Discriminator", "Qubit and CPU", "Encoder and Decoder", "Filter and Pool"], 0, "QGANs train a Quantum Generator against a Classical/Quantum Discriminator in minimax game play."),
        make_q("q-4-1-2", "What advantage do QGANs offer over classical GANs for probability distribution learning?", ["Efficiently represents continuous multi-dimensional quantum state probability distributions", "Requires no training data", "Runs without electricity", "Never overfits"], 0, "QGANs capture quantum correlations and complex multi-variable state distributions."),
        make_q("q-4-1-3", "In a Hybrid QGAN, what quantum circuit component acts as the Generator G(θ_g)?", ["Parameterized Quantum Circuit (PQC) converting latent noise into quantum states", "Classical neural layer", "Measurement buffer", "Hadamard alone"], 0, "A PQC initialized with latent noise acts as the trainable Quantum Generator."),
        make_q("q-4-1-4", "What loss function objective guides QGAN training?", ["Minimax loss min_G max_D V(D, G)", "Mean Squared Error", "L1 Loss", "Huber Loss"], 0, "The minimax objective drives generator optimization to match real data distributions."),
        make_q("q-4-1-5", "What application domain utilizes QGANs for synthetic data generation?", ["Financial Monte Carlo simulation and quantum state tomography", "Word processing", "File compression", "Email filtering"], 0, "QGANs generate synthetic financial asset distributions and quantum state tomographic data.")
    ],
    "lesson-4-2": [
        make_q("q-4-2-1", "What structural feature gives Quantum Convolutional Neural Networks (QCNNs) immunity to Barren Plateaus?", ["O(log N) circuit depth and localized convolution/pooling blocks", "Zero parameters", "Infinite qubits", "No entanglement"], 0, "QCNN logarithmic depth O(log N) prevents exponential gradient concentration."),
        make_q("q-4-2-2", "What operation is executed by a Quantum Pooling Layer in a QCNN?", ["Measures a subset of qubits to conditionally contract active register size", "Flips all bits", "Applies Hadamard to all qubits", "Deletes gates"], 0, "Quantum pooling measures selected qubits to discard redundant dimension while preserving features."),
        make_q("q-4-2-3", "What role do Quantum Convolutional Layers play in QCNNs?", ["Applies local entangling unitaries across adjacent qubit blocks", "Reads hard drive", "Stores classical images", "Cools QPU"], 0, "Quantum convolution layers apply translationally invariant entangling gates across neighboring qubits."),
        make_q("q-4-2-4", "What classification domain is particularly suited for QCNN architectures?", ["Quantum phase transitions and highly entangled quantum state classification", "Text translation", "Audio filtering", "Database sorting"], 0, "QCNNs excel at detecting topological phases of matter and quantum error correction syndromes."),
        make_q("q-4-2-5", "How does QCNN parameter scaling compare to dense QNN parameter scaling as qubit count increases?", ["Scales logarithmically O(log N) instead of exponentially", "Scales exponentially", "Does not scale", "Constant 1 parameter"], 0, "QCNN localized weight sharing drastically reduces trainable parameter counts.")
    ],
    "lesson-4-3": [
        make_q("q-4-3-1", "How does a Quantum Reinforcement Learning (QRL) agent represent its action-value function Q(s, a)?", ["Evaluates observable expectation values on a parameterized variational state |ψ(s, θ)⟩", "Uses a classical SQL table", "Counts clock cycles", "Random guesses"], 0, "State features encode into state |ψ(s, θ)⟩ and expectation values yield predicted Q-values."),
        make_q("q-4-3-2", "What quantum property enhances exploration policies in QRL environment interactions?", ["Quantum state superposition sampling multi-action probability distributions natively", "Classical random numbers", "High CPU speed", "Memory buffers"], 0, "Superposition allows simultaneous exploration sampling across action spaces."),
        make_q("q-4-3-3", "In Quantum Deep Q-Networks (QDQN), how are target network weights updated?", ["Classical Bellman loss gradient descent updating PQC rotation angles θ", "Manual editing", "Random mutation", "Hardware reboot"], 0, "Bellman temporal difference loss L = (r + γ max Q_target - Q_pred)² updates PQC parameters."),
        make_q("q-4-3-4", "What environment types serve as standard benchmarks for QRL algorithms?", ["GridWorld, CartPole, and FrozenLake gym environments", "Video rendering", "Compiler design", "Web scraping"], 0, "CartPole and OpenAI Gym environments benchmark variational QRL agents."),
        make_q("q-4-3-5", "Which QML gradient method evaluates policy gradients for quantum RL agents on hardware?", ["Parameter-Shift Rule", "Finite Differences", "Backprop on CPU", "Genetic search"], 0, "Parameter-Shift computes exact policy gradients on physical QPUs.")
    ],
    "lesson-4-4": [
        make_q("q-4-4-1", "What is the key design philosophy of Hardware-Efficient Ansätze (HEA)?", ["Restricts entangling gates to native physical QPU coupling maps, avoiding costly SWAP gates", "Uses maximum SWAP gates", "Requires fault-tolerant qubits", "Ignores topology"], 0, "HEA matches QPU physical connectivity directly to eliminate transpilation overhead."),
        make_q("q-4-4-2", "Why are SWAP gates costly on NISQ physical hardware?", ["Each SWAP gate decomposes into 3 physical CNOT gates, tripling gate error and decoherence", "SWAP gates take 1 second", "SWAP gates melt hardware", "SWAP gates use too much RAM"], 0, "SWAP gates add significant noise depth to hardware execution."),
        make_q("q-4-4-3", "What native 2-qubit entangling gates are typical on superconducting heavy-hex QPUs?", ["Cross-Resonance (CR) / Echoed Cross-Resonance (ECR) or CZ gates", "Toffoli gates", "CSWAP gates", "Identity"], 0, "IBM hardware uses microwave Cross-Resonance gates as native 2-qubit primitives."),
        make_q("q-4-4-4", "How does HEA compare to problem-inspired ansätze (like UCCSD in chemistry)?", ["HEA has lower circuit depth and fewer SWAP gates, but higher susceptibility to barren plateaus", "HEA is always deeper", "HEA requires 1000 qubits", "They are identical"], 0, "HEA prioritizes low noise depth over problem symmetry."),
        make_q("q-4-4-5", "What layer pattern characterizes a standard HEA circuit?", ["Alternating single-qubit rotation layers (Ry, Rz) and native entangling layers (ECR / CNOT rings)", "Only Hadamard gates", "Only measurement gates", "Random pulses"], 0, "HEA alternates parameterized single-qubit rotations with hardware-native entangler maps.")
    ],
    "lesson-4-5": [
        make_q("q-4-5-1", "What transformation maps second-quantized fermionic creation/annihilation operators to qubit Pauli operators?", ["Jordan-Wigner Transformation or Bravyi-Kitaev Transformation", "Fourier Transform", "Laplace Transform", "Wavelet Transform"], 0, "Jordan-Wigner maps fermionic anti-commutation relations directly into Pauli operator strings."),
        make_q("q-4-5-2", "What electronic structure problem is solved using VQE in quantum chemistry?", ["Electronic ground state energy E₀ and molecular potential energy surface (PES)", "Molecular weight", "Boiling point", "Acoustic frequency"], 0, "VQE computes electronic ground state energy and potential energy curves for molecules."),
        make_q("q-4-5-3", "What chemistry-inspired ansatz enforces electron number and spin conservation symmetries?", ["UCCSD (Unitary Coupled Cluster Single and Double excitations)", "Random Ansatz", "HEA", "Grover Search"], 0, "UCCSD preserves physical electronic spin and particle conservation symmetries."),
        make_q("q-4-5-4", "Why is classical exact diagonalization (FCI) limited to small molecules (e.g. < 20 electrons)?", ["FCI Hilbert space scales exponentially O(2²ᴺ) with orbital count", "Classical computers run out of electricity", "FCI uses wrong math", "FCI is illegal"], 0, "FCI exact classical diagonalization suffers exponential Hilbert space scaling."),
        make_q("q-4-5-5", "Which open-source library integrates Qiskit Nature with quantum chemistry codes like PySCF?", ["Qiskit Nature", "TensorFlow", "Pandas", "Matplotlib"], 0, "Qiskit Nature translates molecular Hamiltonians into qubit operators.")
    ],
    "lesson-4-6": [
        make_q("q-4-6-1", "What speedup does Quantum Amplitude Estimation (QAE) provide over classical Monte Carlo for financial risk analysis?", ["Quadratic speedup: O(1/ε) precision vs classical Monte Carlo O(1/ε²)", "No speedup", "Exponential speedup", "Linear slowdown"], 0, "QAE estimates value-at-risk (VaR) with quadratic sample complexity speedup."),
        make_q("q-4-6-2", "To what mathematical optimization form is portfolio optimization mapped for QAOA execution?", ["QUBO (Quadratic Unconstrained Binary Optimization) / Ising Spin Glass", "Linear Regression", "Logistic Regression", "Neural network"], 0, "Mean-variance portfolio optimization formulates as a binary QUBO matrix."),
        make_q("q-4-6-3", "What financial metric is estimated using QAE in quantitative risk management?", ["Value at Risk (VaR) and Expected Shortfall (Conditional VaR)", "Stock price ticker length", "Employee salaries", "Tax rate"], 0, "QAE estimates tail risk probabilities and VaR metrics with fewer samples."),
        make_q("q-4-6-4", "How are asset returns encoded into quantum states for option pricing circuits?", ["Parameterized rotation gates mapping probability density functions into quantum amplitudes", "Writing text on qubits", "Storing CSV on QPU", "Using classical RAM"], 0, "Probability distribution circuits load asset distribution states into quantum registers."),
        make_q("q-4-6-5", "What enterprise framework provides financial quantum algorithms in Python?", ["Qiskit Finance", "PyTorch", "Django", "Keras"], 0, "Qiskit Finance supplies portfolio optimization, option pricing, and VaR estimation modules.")
    ],
    "lesson-4-7": [
        make_q("q-4-7-1", "What metric measures how uniformly a parameterized quantum ansatz covers the unitary Haar measure?", ["Expressibility (measured via KL divergence D_KL against Haar ensemble)", "Clock speed", "Code length", "RAM size"], 0, "Expressibility quantifies how thoroughly an ansatz explores Hilbert state space."),
        make_q("q-4-7-2", "What is Entangling Capability in QML model benchmarking?", ["The average Meyer-Wallach entanglement measure produced across parameter space", "Number of wires", "Shot count", "Power usage"], 0, "Entangling capability quantifies the average quantum entanglement generated by an ansatz."),
        make_q("q-4-7-3", "What is the purpose of classical dequantization testing on QML benchmarks?", ["Verifies whether a proposed QML algorithm can be efficiently simulated classically without quantum advantage", "Deletes quantum code", "Formats hard drives", "Tests GPU temperature"], 0, "Dequantization checks whether classical kernel methods match QML performance."),
        make_q("q-4-7-4", "Why is cross-validation essential when benchmarking QML classifiers on NISQ hardware?", ["Separates genuine QML generalization performance from NISQ hardware noise overfitting", "Increases training speed", "Decreases qubit count", "Requires no data"], 0, "Cross-validation ensures model predictions generalize beyond training shot noise."),
        make_q("q-4-7-5", "What benchmark suite is widely used for standardized QML model evaluation?", ["PennyLane Datasets and QML Benchmarks", "Geekbench", "AnTuTu", "3DMark"], 0, "PennyLane Datasets provides standardized benchmark datasets and QML metrics.")
    ],
    "lesson-4-8": [
        make_q("q-4-8-1", "What quasi-particles encode non-local quantum information in topological quantum computing?", ["Non-Abelian Anyons (Majorana Zero Modes)", "Electrons", "Photons", "Protons"], 0, "Majorana zero modes and non-Abelian anyons store topological quantum information."),
        make_q("q-4-8-2", "Why are topological braid logic operations inherently fault-tolerant against local thermal noise?", ["Quantum information is stored non-locally in global spacetime braid topology", "Operates at room temperature", "Requires no electricity", "Uses silicon transistors"], 0, "Local noise perturbations cannot unbraid global topological world lines."),
        make_q("q-4-8-3", "What mathematical group describes 2D non-Abelian anyon braid exchanges?", ["Braid Group B_n", "Abelian group Z_2", "Real space R^3", "Symmetric group S_2"], 0, "Braid operations map to non-commutative representations of the Braid Group B_n."),
        make_q("q-4-8-4", "How do anyon exchange operations correspond to quantum logic gate operations?", ["Exchanging (braiding) anyons rotates the degenerate ground state subspace, implementing unitary gates", "Flips classical switches", "Measures temperature", "Cools fridge"], 0, "Spacetime braiding of anyons implements topological unitary gate operations."),
        make_q("q-4-8-5", "Which hardware platform aims to build native topological qubits?", ["Microsoft / Majorana braided semiconductor-superconductor nanowires", "Optical fibers", "Hard drives", "Flash memory"], 0, "Majorana nanowires aim to realize native topological quantum hardware.")
    ],
    "lesson-4-9": [
        make_q("q-4-9-1", "Why are asynchronous queue services (e.g., Celery / Redis) required in cloud QML web backends?", ["QPU hardware execution queues introduce multi-second latency and API rate limits", "CPUs cannot run Python", "To delete data", "To block browsers"], 0, "Asynchronous queues manage QPU execution latency without blocking client HTTP requests."),
        make_q("q-4-9-2", "What cloud architecture hosts hybrid QML microservices in production?", ["Containerized Cloud Run / Kubernetes services with Qiskit / PennyLane runtime handlers", "Single HTML file", "Desktop script", "USB drive"], 0, "Containerized cloud endpoints expose REST/gRPC endpoints for QML inference payloads."),
        make_q("q-4-9-3", "What fallback mechanism handles unexpected QPU hardware offline maintenance in cloud QML apps?", ["Automatic failover routing to GPU-accelerated simulator clusters (e.g., cuQuantum)", "Crashing the app", "Deleting database", "Formatting server"], 0, "GPU simulator clusters provide high-speed fallback during QPU hardware maintenance."),
        make_q("q-4-9-4", "How are secret API keys (IBM Quantum / AWS Braket) secured in full-stack QML applications?", ["Stored in server environment variables (process.env) and accessed via backend proxy endpoints ONLY", "Hardcoded in client React code", "Exposed in URL query params", "Stored in public GitHub"], 0, "API keys must reside strictly on the server backend proxy to protect access credentials."),
        make_q("q-4-9-5", "What REST protocol format is standard for transmitting QML inference payloads between client and server?", ["JSON payloads containing features, parameter arrays, and job IDs", "Raw binary bytes", "XML text", "CSV files"], 0, "JSON request payloads transmit feature vectors and return expectation results.")
    ],
    "lesson-4-10": [
        make_q("q-4-10-1", "What complete workflow defines an end-to-end QML engineering Capstone Project?", ["Problem formulation, dataset feature map encoding, PQC ansatz design, Parameter-Shift training, QPU hardware execution, and cloud deployment", "Writing 1 line of code", "Deleting files", "Buying a server"], 0, "A capstone project integrates full-stack QML development from theory to cloud execution."),
        make_q("q-4-10-2", "How do you verify whether your Capstone QML model achieves genuine Quantum Advantage?", ["Compare accuracy, loss, and sample complexity against classical baseline models (SVM, PyTorch MLP)", "Guess accuracy", "Check line count", "Measure screen size"], 0, "Rigorous comparison against classical baselines measures true quantum performance gains."),
        make_q("q-4-10-3", "What deployment artifact presents your Capstone project execution results to users?", ["Interactive QML Web Application featuring 3D Bloch visualization, circuit builder, and QPU job monitoring", "Text file", "PowerPoint slide", "Screenshot"], 0, "An interactive full-stack QML web app demonstrates real-time inference and QPU execution."),
        make_q("q-4-10-4", "What is the final step in publishing a production-ready Capstone QML application?", ["Deploying full-stack web container to cloud hosting with active QPU cloud connection", "Shutting down laptop", "Deleting code", "Logging out"], 0, "Deploying containerized web applications makes QML tools accessible globally."),
        make_q("q-4-10-5", "What title/badge do students achieve upon completing all 4 Phases and the Capstone project in QML Academy?", ["Quantum Sorcerer / QML Architect", "Novice", "Intern", "Guest"], 0, "Mastering all 4 phases earns the highest Quantum Sorcerer / QML Architect badge.")
    ]
}

print("Phase 4 quizzes loaded successfully.")
